# Node.js with Angular
# Build a Node.js project that uses Angular.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- master

pool:
  vmImage: ubuntu-latest



jobs:
- job: Prepare_Environment
  steps:
  - task: NodeTool@0
    inputs:
      versionSpec: '14.18.1'
    displayName: 'Install Node.js'

- job: Build_Issuer
  variables:
  - group: ACAPy-Issuer-Frontend
  steps:
  - script: |
      cd ./agent
      npm install -g @angular/cli
      npm install
      ng build --configuration=production
    displayName: 'npm install and build'

  - task: replacetokens@3
    inputs:
      targetFiles: $(System.DefaultWorkingDirectory)/agent/dist/**/main*.js
      tokenPrefix: '#{'
      tokenSuffix: '}#'

  - publish: $(System.DefaultWorkingDirectory)/agent/dist
    artifact: issuer_dist

- job: Build_Holder
  variables:
  - group: ACAPy-Holder-Frontend
  steps:
  - script: |
      cp ./agent-specific/holder/index.html ./agent/src/index.html
      cp ./agent-specific/holder/nav.component.html ./agent/src/app/components/nav/nav.component.html 
      cp ./agent-specific/holder/interceptor.service.ts ./agent/src/app/services/interceptor.service.ts
      cd ./agent
      ng build --configuration=production
    displayName: 'npm install and build'

  - task: replacetokens@3
    inputs:
      targetFiles: $(System.DefaultWorkingDirectory)/agent/dist/**/main*.js
      tokenPrefix: '#{'
      tokenSuffix: '}#'

  - publish: $(System.DefaultWorkingDirectory)/agent/dist
    artifact: holder_dist