version: 0.2

phases:
  install:
    on-failure: ABORT
    runtime-versions:
      nodejs: 14.x
  build:
    on-failure: ABORT
    commands:
      - cd ./agent
      - npm install -g @angular/cli@12.2.13
      - npm install
      - ng build
      - echo "show path"
      - pwd
      - cd ./dist
      - ls -al
      - cd ./issuer-controller
      - ls -al
  post_build:
    commands:
      - echo "show path again"
      - pwd
      - cd ./dist
      - ls -al
      - cd ./issuer-controller
      - ls -al
      - aws s3 cp --recursive ./dist/issuer-controller/* s3://demo-issuer101/