version: 0.2

phases:
  install:
    on-failure: ABORT
    runtime-versions:
      nodejs: 14.x
  build:
    on-failure: ABORT
    commands:
      - cd ./agent
      - npm install -g @angular/cli
      - npm install
      - ng build
artifacts:
  files:
    - agent/dist/issuer-controller/*
  name: issuer