version: 0.2

phases:
  install:
    on-failure: ABORT
    runtime-versions:
      nodejs: 14.x
  build:
    on-failure: ABORT
    commands:
      - cd ./agent
      - npm install -g @angular/cli@12.2.13
      - npm install
      - ng build
  post_build:
    commands:
      - aws s3 cp --recursive ./dist/issuer-controller/* s3://demo-issuer101/