version: "3"
services:
  issuer:
    image: bcgovimages/aries-cloudagent:py36-1.16-0_0.6.0
    container_name: issuer
    environment:
      ACAPY_ADMIN_INSECURE_MODE: "true"
      ACAPY_AUTO_PROVISION: "true"
      ACAPY_DEBUG_CONNECTIONS: "true"
      ACAPY_ENDPOINT: "http://issuer:8000"
      ACAPY_LABEL: "Issuer"
      ACAPY_LOG_LEVEL: "info"
      ACAPY_NO_LEDGER: "true"
      ADMIN_PORT: "8001"
      AGENT_PORT: "8000"
    entrypoint: /bin/bash
    command: ["-c",
        "aca-py start \
        --admin '0.0.0.0' 8001 \
        --inbound-transport http '0.0.0.0' 8000 \
        --outbound-transport http \
        --wallet-type indy \
        --wallet-name issuerwallet \
        --wallet-key issuerkey \
        --auto-provision \
        --auto-accept-invites \
        --auto-accept-requests \
        --auto-ping-connection "
    ]
    ports:
      - "8001:8001"

  holder:
    image: bcgovimages/aries-cloudagent:py36-1.16-0_0.6.0
    container_name: holder
    environment:
      ACAPY_ADMIN_INSECURE_MODE: "true"
      ACAPY_AUTO_PROVISION: "true"
      ACAPY_DEBUG_CONNECTIONS: "true"
      ACAPY_ENDPOINT: "http://holder:9000"
      ACAPY_LABEL: "Holder"
      ACAPY_LOG_LEVEL: "info"
      ACAPY_NO_LEDGER: "true"
      ADMIN_PORT: "9001"
      AGENT_PORT: "9000"
    entrypoint: /bin/bash
    command: ["-c",
        "aca-py start \
        --admin '0.0.0.0' 9001 \
        --inbound-transport http '0.0.0.0' 9000 \
        --outbound-transport http \
        --wallet-type indy \
        --wallet-name issuerwallet \
        --wallet-key issuerkey \
        --auto-provision \
        --auto-accept-invites \
        --auto-accept-requests \
        --auto-ping-connection "
    ]
    ports:
      - "9001:9001"